# Generated by Django 5.1 on 2024-09-10 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_rename_user_admi_user_user_adm_alter_user_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='username',
        ),
    ]
