# Generated by Django 5.1 on 2024-10-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0010_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
